---
title: "Compute Effect Estimates for Survival Models"
author: "Erin M. Ochoa & Marisa C. Ross"
date: "2023/10/02"
output: html_document
---

```{r setup, include=FALSE}
library(glue)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

```{r declare_constants}
# Declare the directory where the simple results files are located.
results_dir <- "../../results"

fname_out <- "estimates_yob_balanced_sampling_geoT-mu-ate_long-term.csv"

# Declare list of months for which we want mu and ATE estimates
num_months_list <- c(6, 12, 18)
```

```{r f.get_local_row}
get_local_row <- function(local_results, num_months_list){
  # This function takes in a single results object and returns a row of the
  # model details and estimates.
  
  # Pull out the parameters.
  local_params <- local_results$parameters
  
  # Get the model specification.
  local_estimates <- get_model_spec(local_params)
  
  for(num_months in num_months_list){
    # Augment the local_spec with estimates for mu and ATE for num_months.
    local_estimates <- local_estimates %>% 
                       compute_estimates(local_results$table, num_months)
  }
  return(local_estimates)
}
```

```{r f.get_model_spec}
get_model_spec <- function(params){
  # This function pulls out the model specification details from the parameters
  # slot of the results object.
  data.frame(organization = params$main$organization,
             status_type = params$main$status_type,
             sample_size_tx = params$bart$sample_data %>% 
                                filter(tx == 1) %>% nrow(),
             sample_size_cg = params$bart$sample_data %>% 
                                filter(tx == 0) %>% nrow(),
             sample_size_all = params$bart$sample_data %>% nrow(),
             seed = params$main$seed,
             geo_cred = params$main$geo_cred,
             dosage = params$main$dosage,
             dropout = params$main$dropout)
}
```

```{r f.compute_estimates}
compute_estimates <- function(local_spec, surv_table, num_months){
  # This function adds the model estimates for the given number of months to the
  # row for the local results.
  
  # Get df of 2 rows (tx & cg) with mu estimates for the given num_weeks.
  local_df <- get_local_df(surv_table, num_months)
  
  # Augment the model specification row with the estimates and return.
  build_local_row(local_spec, local_df, num_months)
}
```

```{r f.build_local_row}
build_local_row <- function(local_spec, local_df, num_months){
  # This function takes in a row with a model specification (organization, type
  # of survival event, etc.), a number of months, and a df of mu estimates for
  # the given number of months and returns the specification row augmented with
  # estimates for mu and ATE, presented in various formats.
  
  # Pull out the estimates at the local time.
  tx_mu <- local_df %>% filter(group == "tx") %>% pull(mu)
  cg_mu <- local_df %>% filter(group == "cg") %>% pull(mu)
  
  # Compute percentage-difference (treatment compared to control).
  pct_delta <- (tx_mu - cg_mu) / cg_mu * 100
  
  # Estimate the average treatment effect, as well as some transformations.
  ate <- tx_mu - cg_mu # ATE
  ate_pp <- ate * 100 # ATE in percentage points
  ate_hr <- tx_mu / cg_mu # Hazard ratio: how likely is tx to survive compared to cg at num_weeks?
  
  # Add the estimates to the model specification and return.
  local_spec %>%
    mutate(!!sym(glue("mean_surv_prob.tx_{num_months}m")) := tx_mu,
           !!sym(glue("mean_surv_prob.cg_{num_months}m")) := cg_mu,
           !!sym(glue("mean_surv_pct.tx_{num_months}m")) := tx_mu * 100,
           !!sym(glue("mean_surv_pct.cg_{num_months}m")) := cg_mu * 100,
           !!sym(glue("pct_delta.{num_months}m")) := pct_delta,
           !!sym(glue("ate.{num_months}m")) := ate,
           !!sym(glue("ate_pp.{num_months}m")) := ate_pp,
           !!sym(glue("ate_hr.{num_months}m")) := ate_hr)
}
```

```{r}
get_local_df <- function(surv_table, num_months){
  # Get a dataframe of the y-values at the desired number of weeks.
  
  # Compute the approximate number of weeks in the given months.
  num_weeks <- (num_months / 12 * 52) %>% round()
  
  # Find out if the number of weeks is in the table (so don't need to estimate
  # with the slope).
  num_weeks_in_table <- num_weeks %in% surv_table$time
  
  if(num_weeks_in_table){
    # If the desired time is already in the table, pull out those rows.
    local_df <- surv_table %>% 
                filter(time == num_weeks) %>% 
                transmute(group, time, mu)
  } else{
    # If the desired time is not in the table, estimate the mu values using the
    # times immediately before and after to find the slope and y-val per group.
    local_df <- mu_from_slope(surv_table, num_weeks)
  }
  return(local_df)
}
```

```{r f.mu_from_slope}
mu_from_slope <- function(surv_table, num_weeks){
  # This function uses the two times on either side of the desired time to find
  # the slope between the two and then estimate the survival proportion at that
  # point.
  
  # Initialize an empty dataframe to store the results.
  local_df <- data.frame()
  
  for(grp in c("tx", "cg")){
    # Find the rows with the last times below and above the desired point.
    group_rows <- bind_rows(surv_table %>% 
                               filter(group == grp, time < num_weeks) %>% 
                               slice_max(time),
                            surv_table %>% 
                               filter(group == grp, time > num_weeks) %>% 
                               slice_min(time))
    
    # Get the slope between the two times.
    slope_coef <- coef(lm(mu ~ time, group_rows))[["time"]]
    
    # Now that we have the slope, we need to find the y-value at num_weeks.
    low_weeks <- group_rows %>% slice_min(time) %>% pull(time)
    delta_weeks <- num_weeks - low_weeks
    est <- group_rows %>% 
             slice_min(time) %>% 
             pull(mu) + (delta_weeks * slope_coef)
    
    # Add it to the local data.frame; empty slot for the estimate.
    local_df <- local_df %>% 
                  bind_rows(data.frame(group = grp,
                                       time = num_weeks,
                                       mu = est))
  }
  return(local_df)
}
```

```{r f.build_estimates_table}
build_estimates_table <- function(results_dir, num_months_list){
  # This functions takes in a directory of results files, reads in the simple
  # results files, and builds a table with estimates and effect sizes.
  
  # Get the names of the files to read in.
  results_names <- dir(results_dir, "^results_surv_simple.")
  
  # Initialize an empty dataframe to hold the estimates.
  df.estimates <- data.frame()
  
  # Read in each simple-results file in the results directory. For each, pull out
  # the table, compute the estimates, and add to a dataframe of estimates.
  for(fname in results_names){
    local_results <- readRDS(file.path(results_dir, fname))
    
    # Add a row with estimates for the local results object.
    df.estimates <- df.estimates %>% 
                    bind_rows(get_local_row(local_results, num_months_list))
  }
  return(df.estimates)
}
```

```{r f.explanations}
get_estimate_descriptions <- function(){
  # Build a dataframe with the name and description of each estimate; return.
  data.frame(estimate = "Mean survival rate (out of 1) at given time (in months; higher number is the better outcome)",
             estimate_pct = "Mean survival rate (in percentage) at a given time (in months; higher number is the better outcome)",
             pct_delta = "Percent difference in mean survival rate for treatment compared to control (negative values are unfavorable)",
             ate_delta = "Difference in P(survival) for treatment compared to control (negative values are unfavorable)",
             ate_pp = "Difference in P(survival) for treatment compared to control in percentage points (negative values are unfavorable)",
             ate_hr = "How likely treatment is to survive compared to control (values below 1 are unfavorable)") %>% 
    pivot_longer(everything(), names_to = "Estimate_Name", values_to = "Estimate_Description")
}
```

```{r estimates}
# Get the estimates table.
df.estimates <- build_estimates_table(results_dir, num_months_list)

# Write results.
write.csv(df.estimates, file.path(results_dir, fname_out), row.names = FALSE)

# Write CSV of estimate names with their descriptions.
get_estimate_descriptions() %>% 
  write.csv(file.path(results_dir, "estimate_descriptions.csv"),
            row.names = FALSE)
```
